version: 0.0
os: linux
files:
  - source: /
    destination: /opt/testing3
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 4755
hooks:
  BeforeInstall:
#    - location: _scripts/erase-files.sh
#      timeout: 60
#      runas: root
    - location: _scripts/stop-forever.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: _scripts/npm-install.sh
      timeout: 480
      runas: ec2-user
  ApplicationStart:
    - location: _scripts/start-forever.sh
      timeout: 300
      runas: ec2-user
